### ISSUE TITLE
Navigation logic

### ISSUE THREAD

**Issue by mkucmus** [elkmod/SwagVueStorefront#23]
### Introduction
There are two (or even more) aspects of the navigation we know so far: 

1. main navigation (top navigation at the top of the shop)
2. navigation widget (as a cms block)

Though the top navigation behavior is well known, and there are no questions about it, for now, the navigation widget may behave differently depending on usage, and place it's being used. And there are some questions about it

## questions
1. With which rootID the navigation widget should start being on the specific category (for instance /Sports/Basketball ? Should we show entire navigation with only current category bolded (marked by some sort of flag) or just start showing the navigation with rootID as the current category has. 
2.  No matter what's the answer to the question above, Could we fetch the entire navigation inside the cms/page resolver's response? Now we've got only the information that navigation slot is being used in specific place, but with no data inside. It would be very comfortable to get the navigation hydrated as well as we do with the media is or other parts of the cms.

**Comment by elkmod** [comment]
I dug into this and, surprisingly, the navigation block is really simply a block mirroring the category navigation (highlighting the currently active one) - see the example below. There is no different "root" that you can set. 

![image](https://user-images.githubusercontent.com/7780750/68837047-07a39200-06bc-11ea-9133-6fef4384e1d7.png)

Hence we could fetch the navigation along with the page, but for now, I would prefer not to do so, as you should have the current navigation (along with the highlighting due to the currently active category) already present within the application.

See our implementation of the block behavior - [cms-element-category-navigation](https://github.com/shopware/platform/blob/master/src/Storefront/Resources/views/element/cms-element-category-navigation.html.twig)
